# Spring Boot 配置
server:
  port: 8160

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/campus_imaotai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
    database: 0
    # password:  # 如有密码请取消注释并填写

# 日志配置
logging:
  level:
    root: info

# 其他自定义配置可根据实际需求补充 