version: '3.8'

services:
  xianyu-app:
    image: registry.cn-shanghai.aliyuncs.com/zhinian-software/xianyu-auto-reply:1.0
    container_name: xianyu-auto-reply
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 数据持久化
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./backups:/app/backups:rw
    environment:
      - TZ=Asia/Shanghai
      - DOCKER_ENV=true
      - PYTHONUNBUFFERED=1
      - ADMIN_USERNAME=cyj          # 自定义用户名
      - ADMIN_PASSWORD=cyj123456  # 自定义密码
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
