version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: campus-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: campus_imaotai
      TZ: Asia/Shanghai
    ports:
      - "13306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:6.2
    container_name: campus-redis
    restart: always
    ports:
      - "16379:6379"
    volumes:
      - ./redis_data:/data

  campus-server:
    image: oddfar/campus-imaotai
    container_name: campus-server
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 8160
      spring.config.additional-location: /home/campus/conf/application-prod.yml
    ports:
      - "8160:8160"
    volumes:
      - ./conf:/home/campus/conf
      - ./jar:/home/campus/jar

  nginx:
    image: nginx:latest
    container_name: campus-nginx
    restart: always
    depends_on:
      - campus-server
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  mysql_data:
  redis_data: 