version: '3.8'

services:
  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./html:/output
    environment:
      - NODE_ENV=production
      - VUE_APP_BASE_API=/prod-api
    command: sh -c "rm -rf /output/* && cp -r /app/vue_campus_admin/dist/* /output/ && echo 'Frontend files copied successfully'"

  backend-build:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./jar:/output
    command: sh -c "rm -rf /output/* && cp -r /app/campus-modular/target/campus-modular*.jar /output/ && echo 'Backend jar copied successfully'"

  mysql:
    image: mysql:5.7
    container_name: campus-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: campus_imaotai
      TZ: Asia/Shanghai
    volumes:
      - ./mysql_data:/var/lib/mysql/
      - ./mysql/conf:/etc/mysql/conf.d/
      - ./db:/docker-entrypoint-initdb.d
      - ./logs/mysql:/logs
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1',
      '--max_connections=1000',
      '--wait_timeout=31536000'
    ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  redis:
    image: redis:6.2.12
    container_name: campus-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data:/data
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  campus-server:
    image: oddfar/campus-imaotai
    container_name: campus-server
    restart: always
    ports:
      - "8160:8160"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 8160
      SPRING_PROFILES_ACTIVE: prod
      spring.config.additional-location: /home/campus/conf/application-prod.yml
      JAVA_OPTS: "-Xms512m -Xmx512m -Djava.security.egd=file:/dev/./urandom"
    volumes:
      - ./conf:/home/campus/conf
      - ./jar:/home/campus/jar
      - ./logs/server:/home/campus/logs
      - ./upload:/home/campus/upload
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8160/actuator/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 15
      start_period: 180s

  nginx:
    image: nginx:1.23.4
    container_name: campus-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      campus-server:
        condition: service_healthy
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
  redis_data:

networks:
  default:
    driver: bridge 