version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.101.1
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    network_mode: host
    environment:
      - N8N_DEFAULT_LOCALE=zh-CN
      # - N8N_RUNNERS_ENABLED=true # 启用多进程，单机版不要开启，否则会报403 Runner错误
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=123456
      - N8N_ENCRYPTION_KEY=hr3b72wldcnbw728ehs8d3bc29dhbd82
      - N8N_SECURE_COOKIE=false
      - TZ=Asia/Shanghai
      - GENERIC_TIMEZONE=Asia/Shanghai
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - NODE_OPTIONS=--max-old-space-size=512
      - N8N_LOG_LEVEL=debug
      - N8N_LOG_OUTPUT=console
      - N8N_LOG_FORMAT=plain
      - N8N_DIAGNOSTICS_ENABLED=false # 禁止收集和发送任何遥测数据。
      #### 开发环境时使用#####
      # - N8N_HOST=localhost
      # - N8N_PROTOCOL=http
      - N8N_PORT=5678
      #### cloudflare的work代理时使用 START###
      - N8N_HOST=n8n-in.10023456.xyz
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n-in.10023456.xyz/
      - N8N_PUSH_BACKEND=websocket
      - VUE_APP_URL_BASE_WEBSOCKET=wss://n8n-in.10023456.xyz
      #### cloudflare的work代理时使用 END###
      # ✅ 设置容器内 HTTP/HTTPS 请求都走宿主机代理（FlClash 默认 SOCKS5 为 7890，HTTP 为 7890）
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - NO_PROXY=localhost,127.0.0.1
    volumes:
      - ./data:/home/node/.n8n
      - ./editor-ui-dist:/usr/local/lib/node_modules/n8n/node_modules/n8n-editor-ui/dist
    # 注意：限制内存是在3+版本中使用的，2.x版本中使用的是N8N_MAX_OLD_SPACE_SIZE
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M

